package={name='app', version='0.0.0', edition='2021', autoexamples=false, default-run='text'}
example=[
 {name='empty', path='examples/empty.rs'}
 #{name='text', path='examples/text.rs', required-features=['text']},
 #{name='compose', path='examples/compose.rs', required-features=['text']},
 #{name='edit', path='examples/edit.rs', required-features=['edit']},
 #{name='plot', path='examples/plot.rs', required-features=['plot']}
]
bin=[{name='text',path='examples/text.rs',required-features=['text']}]

[features]
font=['derive-more','ttf-parser','kurbo','image/num']
text=['unicode-segmentation','iter','font','derive-more','text-size']
#edit=['text']
#plot=['text','itertools']
default=['text']

[dependencies]
fehler='*'
iter={git='https://github.com/Matthias-Fauconneau/iter', optional=true}
vector= {git='https://github.com/Matthias-Fauconneau/vector'}
num={git='https://github.com/Matthias-Fauconneau/num'}
derive-more={version='*', package='derive_more', optional=true}
owning-ref={version='*', package='owning_ref'}
futures-lite='*'
futures={version='*', package = 'futures-util'} # SelectAll, select_all, LocalBoxStream
rustix='*'
async-io='*'
memmap={version='*'}
dirs='*'
xy={git='https://github.com/Matthias-Fauconneau/xy'}
image={git='https://github.com/Matthias-Fauconneau/image'}
client-toolkit={version='*', package='smithay-client-toolkit', default-features=false}

piet-gpu-hal={git='https://github.com/linebender/piet-gpu'}
raw-window-handle='*'
wayland-client={version='*', features=['use_system_lib']}
piet-gpu={git='https://github.com/linebender/piet-gpu'}
piet='^0.2'

kurbo={version='*', optional=true}
ttf-parser={version='*', optional=true}
unicode-segmentation={version='*', optional=true}
text-size={version='*', optional=true}

trace={git='https://github.com/Matthias-Fauconneau/trace', optional=true}
itertools={version='*', optional=true}

[patch.'https://github.com/linebender/piet-gpu']
piet-gpu-hal={path='../piet-gpu/piet-gpu-hal'}
piet-gpu={path='../piet-gpu/piet-gpu'}