cargo-features = ['edition2024']
package={name='ui', version='0.0.0', edition='2024'}
example=[
 {name='empty', path='examples/empty.rs'},
 {name='glyph', path='examples/glyph.rs', required-features=['text']},
 {name='text', path='examples/text.rs', required-features=['text']},
 {name='compose', path='examples/compose.rs', required-features=['text','edit']},
 {name='edit', path='examples/edit.rs', required-features=['edit']},
 {name='plot', path='examples/plot.rs', required-features=['plot']},
]

[features]
default=['wayland','background']

font=['fehler','dep:derive-more','dep:owning-ref','dep:rustybuzz','kurbo','dep:cfg-if','rustix','vector/int_roundings','image/slice_take']
text=['fehler','dep:derive-more','dep:text-size','dep:unicode-segmentation','font','dep:rustybuzz','dep:glob','array_methods']
edit=['text']#,'xcursor'
plot=['text','dep:itertools','array_windows','coroutines']
graphic=['font','dep:rustybuzz','coroutines']

vulkan=['dep:ash']
wayland=['rustix/net','dep:nix','dep:drm']
softbuffer=['dep:softbuffer','dep:winit']

background=[]

kurbo=['dep:kurbo']
xcursor=['dep:xcursor']
rustix=['dep:rustix']
fehler=['dep:fehler']

array_methods=[]
array_windows=[]
coroutines=[]

[dependencies]
fehler={version='*', optional=true}
derive-more={version='*', package='derive_more', optional=true, features=['deref']}
itertools={version='*', optional=true}
cfg-if={version='*', optional=true}
owning-ref={version='*', package='owning_ref', optional=true}
bytemuck='*'

num= {git='https://github.com/Matthias-Fauconneau/num'}
vector= {git='https://github.com/Matthias-Fauconneau/vector'}
trace={git='https://github.com/Matthias-Fauconneau/trace', optional=true}

kurbo={version='*', optional=true}

linux-raw-sys='*'
rustix={version='*', features=['fs','mm','time','event','use-libc'], optional=true} # Currently broken without libc
#dirs='*'
nix={version='*', default-features = false, features = ['socket','uio'], optional=true}
drm={version='*', optional=true}

image={git='https://github.com/Matthias-Fauconneau/image'}
text-size={version='*', optional=true}
unicode-segmentation={version='*', optional=true}
rustybuzz={version='*', optional=true}
glob={version='*', optional=true}
xcursor={version='*', optional=true}
ash={version='*', optional=true, default-features=false, features = ['linked','debug']}
winit={version='*', optional=true}
softbuffer={git='https://github.com/rust-windowing/softbuffer', optional=true, default-features=false, features = ['wayland']}

#[dev-dependencies]
image-io={package='image', version='*', optional=true, default-features=false, features=['png']}

#[target.'cfg(not(target_os="windows"))'.features]
#default = ['wayland']
#[target.'cfg(target_os="windows")'.features]
#default = ["softbuffer"]
