cargo-features= ['edition2021']
package= {name='ui', version='0.0.0', edition='2021'}
example = [
	{name= 'window', path= 'examples/window.rs', required-features= ['app']},
	{name= 'text', path= 'examples/text.rs', required-features= ['app','text']},
	{name= 'compose', path= 'examples/compose.rs', required-features= ['edit']},
	{name= 'edit', path= 'examples/edit.rs', required-features= ['app','edit']}
]

[features]
widget= ['fehler','error','client-toolkit']
app= ['fehler','num','futures','async-io','client-toolkit','widget','vector']
font= ['derive-more','fehler','ttf-parser','kurbo','image/num']
graphic= ['fehler','widget','font']
font-file= ['font','owning-ref','memmap']
text= ['unicode-segmentation','iter','num','font','widget','font-file','derive-more','text-size']
color= ['vector']
plot= ['text','color','itertools']
default= ['color','text','app']

[dependencies]
iter={git='https://github.com/Matthias-Fauconneau/iter', optional=true}
num={git='https://github.com/Matthias-Fauconneau/num', optional=true}
vector= {git='https://github.com/Matthias-Fauconneau/vector', optional=true}
cfg-if='*'
fehler= {version='*', optional=true} # #[throws] expects {{root}}::fehler
derive-more= {version='*', package='derive_more', optional=true}
owning-ref= {version='*', package='owning_ref', optional=true}
error= {git='https://github.com/Matthias-Fauconneau/error', optional=true}
futures-lite='*'
futures= {version='*', optional=true, package = 'futures-util'} # SelectAll, select_all, LocalBoxStream
rsix= '*'
async-io= {version='*', optional=true}

memmap= {version='*', optional=true}
dirs= '*'
xy= {git='https://github.com/Matthias-Fauconneau/xy'}
image= {git='https://github.com/Matthias-Fauconneau/image'}
client-toolkit= {version='*', package='smithay-client-toolkit', optional=true, default-features=false}

kurbo= {version='*', optional=true}
ttf-parser= {version='*', optional=true}
unicode-segmentation= {version='*', optional=true}
text-size= {version='*', optional=true}

trace= {git='https://github.com/Matthias-Fauconneau/trace', optional=true}
itertools= {version='*', optional=true}
