package={name='ui', version='0.0.0', edition='2021'}
example=[
 #{name='empty', path='examples/empty.rs'}
 {name='text', path='examples/text.rs', required-features=['text']},
 #{name='compose', path='examples/compose.rs', required-features=['text']},
 {name='edit', path='examples/edit.rs', required-features=['edit']},
]

[features]
font=['derive-more','memmap','owning-ref','ttf-parser','kurbo']
text=['derive-more','text-size','unicode-segmentation','font','rustybuzz']
edit=['text','xcursor']
plot=['text','itertools']

[dependencies]
fehler='*'
derive-more={version='*', package='derive_more', optional=true}
itertools={version='*', optional=true}
owning-ref={version='*', package='owning_ref', optional=true}
bytemuck='*'

num= {git='https://github.com/Matthias-Fauconneau/num'}
vector= {git='https://github.com/Matthias-Fauconneau/vector'}
trace={git='https://github.com/Matthias-Fauconneau/trace', optional=true}

kurbo={version='*', optional=true}

linux-raw-sys='0.1'
rustix={version='*', features=['fs','mm','time']}
dirs='*'
memmap={version='*', package='memmapix', optional=true}
nix={version='*', default-features = false, features = ['socket','uio']}
drm='*'

image={git='https://github.com/Matthias-Fauconneau/image'}
text-size={version='*', optional=true}
unicode-segmentation={version='*', optional=true}
ttf-parser={version='0.17', optional=true}
rustybuzz={version='*', optional=true}
xcursor={version='*', optional=true}
