cargo-features = ['edition2024']
package={name='ui', version='0.0.0', edition='2024'}

[dependencies]
winit={version='*'}
softbuffer={version='*', default-features=false, features = ['wayland']}
vector= {git='https://github.com/Matthias-Fauconneau/vector', features=['int_roundings']}
image={git='https://github.com/Matthias-Fauconneau/image', features=['slice_take']}
rustix={version='*', features=['fs','mm']}
fehler='*'
text-size='*'
unicode-segmentation='*'
rustybuzz='*'
derive_more={version='*', features=['deref']}
owning_ref='*'
kurbo='*'
glob='*'