package={name='ui', version='0.0.0', edition='2021'}
example=[
 {name='empty', path='examples/empty.rs'},
 {name='glyph', path='examples/glyph.rs', required-features=['text']},
 {name='text', path='examples/text.rs', required-features=['text']},
 {name='compose', path='examples/compose.rs', required-features=['text','edit']},
 {name='edit', path='examples/edit.rs', required-features=['edit']},
 {name='plot', path='examples/plot.rs', required-features=['plot']},
]

[features]
font=['derive-more','owning-ref','rustybuzz','kurbo','cfg-if']
text=['derive-more','text-size','unicode-segmentation','font','rustybuzz','glob']
edit=['text','xcursor']
plot=['text','itertools']
graphic=['font','rustybuzz']
vulkan=['ash']
softbuffer=['dep:softbuffer','dep:winit']

[dependencies]
fehler='*'
derive-more={version='*', package='derive_more', optional=true}
itertools={version='*', optional=true}
cfg-if={version='*', optional=true}
owning-ref={version='*', package='owning_ref', optional=true}
bytemuck='*'

num= {git='https://github.com/Matthias-Fauconneau/num'}
vector= {git='https://github.com/Matthias-Fauconneau/vector'}
trace={git='https://github.com/Matthias-Fauconneau/trace', optional=true}

kurbo={version='*', optional=true}

linux-raw-sys='0.1'
rustix={version='*', features=['fs','mm','time']}
dirs='*'
drm={version='*', optional=true}

image={git='https://github.com/Matthias-Fauconneau/image'}
text-size={version='*', optional=true}
unicode-segmentation={version='*', optional=true}
rustybuzz={version='*', optional=true}
glob={version='*', optional=true}
xcursor={version='*', optional=true}
ash={version='*', optional=true, default-features = false, features = ['linked','debug']}
image-io={package='image', version='*', optional=true, default-features=false, features=['png']}
winit={version='*', optional=true}
softbuffer={git='https://github.com/rust-windowing/softbuffer', optional=true}
font-kit={version='*', optional=true}

[patch.'https://github.com/Matthias-Fauconneau/image']
image={path='../image'}
