package={name='ui', version='0.0.0', edition='2021'}
example=[
 {name='empty', path='examples/empty.rs'},
 {name='glyph', path='examples/glyph.rs', required-features=['text']},
 {name='text', path='examples/text.rs', required-features=['text']},
 {name='compose', path='examples/compose.rs', required-features=['text','edit']},
 {name='edit', path='examples/edit.rs', required-features=['edit']},
 {name='plot', path='examples/plot.rs', required-features=['plot']},
]

[features]
font=['fehler','derive-more','owning-ref','rustybuzz','kurbo','cfg-if','int_roundings','rustix','image/lazy_cell','image/new_uninit','image/slice_take']
text=['fehler','derive-more','text-size','unicode-segmentation','font','rustybuzz','glob','lazy_cell','array_methods']
edit=['text','xcursor']
plot=['text','itertools','array_windows','generators']
graphic=['font','rustybuzz']
vulkan=['ash']
wayland=['rustix/net','nix','drm','image/lazy_cell']
softbuffer=['dep:softbuffer','dep:winit','image/lazy_cell']
default=['wayland']

int_roundings=['vector/int_roundings']
lazy_cell=[]
array_methods=[]
array_windows=[]
generators=[]

[dependencies]
fehler={version='*', optional=true}
derive-more={version='*', package='derive_more', optional=true, features=['deref']}
itertools={version='*', optional=true}
cfg-if={version='*', optional=true}
owning-ref={version='*', package='owning_ref', optional=true}
bytemuck='*'

num= {git='https://github.com/Matthias-Fauconneau/num',tag='0'}
vector= {git='https://github.com/Matthias-Fauconneau/vector',tag='0'}
trace={git='https://github.com/Matthias-Fauconneau/trace', optional=true}

kurbo={version='*', optional=true}

linux-raw-sys='*'
rustix={version='*', features=['fs','mm','time','event','use-libc'], optional=true} # Currently broken without libc
#dirs='*'
nix={version='*', default-features = false, features = ['socket','uio'], optional=true}
drm={version='*', optional=true}

image={git='https://github.com/Matthias-Fauconneau/image',tag='0'}
text-size={version='*', optional=true}
unicode-segmentation={version='*', optional=true}
rustybuzz={version='*', optional=true}
glob={version='*', optional=true}
xcursor={version='*', optional=true}
ash={version='*', optional=true, default-features=false, features = ['linked','debug']}
winit={version='*', optional=true}
softbuffer={git='https://github.com/rust-windowing/softbuffer', optional=true, default-features=false, features = ['wayland']}

#[dev-dependencies]
image-io={package='image', version='*', optional=true, default-features=false, features=['png']}

#[target.'cfg(not(target_os="windows"))'.features]
#default = ['wayland']
#[target.'cfg(target_os="windows")'.features]
#default = ["softbuffer"]
