package={name='ui', version='0.0.0', edition='2024'}

[dependencies]
vector= {git='https://github.com/Matthias-Fauconneau/vector', features=['int_roundings']}
#image={git='https://github.com/Matthias-Fauconneau/image', features=['slice_take']}
image={path='../image', features=['slice_take']}
#rustix={git='https://github.com/Matthias-Fauconneau/rustix', features=['fs','mm','net','event']} # rustix: 0.4 -> same as drm:
rustix={version='*', features=['fs','mm','net','event']} # rustix: 0.4 -> same as drm:
text-size='*'
unicode-segmentation='*'
rustybuzz='*'
derive_more={version='*', features=['deref']}
owning_ref='*'
kurbo='*'
glob='*'
bytemuck='*'
drm='*'

[features]
text=[]
graphic=[]

#[patch.crates-io]
#rustix={git='https://github.com/Matthias-Fauconneau/rustix'} # rustix: 0.4 -> same as drm:

[patch.'https://github.com/Matthias-Fauconneau/image']
image={path='../image'}
