package={name='ui', version='0.0.0', edition='2021', autoexamples=false, default-run='text'}
example=[
 {name='empty', path='examples/empty.rs'}
 #{name='text', path='examples/text.rs', required-features=['text']},
 #{name='compose', path='examples/compose.rs', required-features=['text']},
 #{name='edit', path='examples/edit.rs', required-features=['edit']},
 #{name='plot', path='examples/plot.rs', required-features=['plot']}
]
bin=[{name='text',path='examples/text.rs',required-features=['text']}]

[features]
font=['ttf-parser','derive-more','memmap','owning-ref']
text=['unicode-segmentation','iter','font','derive-more','text-size']
edit=['text']
window-handle=['wayland-backend/client_system']
#plot=['text','itertools']
default=['text','window-handle']

[dependencies]
fehler='*'
futures-lite='*'
futures={version='*', package = 'futures-util'} # SelectAll, select_all, LocalBoxStream
async-io='*'
rustix={git='https://github.com/bytecodealliance/rustix'}
dirs='*'

vector= {git='https://github.com/Matthias-Fauconneau/vector'}
xy= {git='https://github.com/Matthias-Fauconneau/xy'}
num= {git='https://github.com/Matthias-Fauconneau/num'}

image={git='https://github.com/Matthias-Fauconneau/image'}
ttf-parser={version='*', optional=true}
derive-more={version='*', package='derive_more', optional=true}
owning-ref={version='*', package='owning_ref', optional=true}
memmap={version='*', optional=true}

iter={git='https://github.com/Matthias-Fauconneau/iter', optional=true}
unicode-segmentation={version='*', optional=true}
text-size={version='*', optional=true}

#client-toolkit={version='*', package='smithay-client-toolkit', default-features=false}
wayland-protocols={git='https://github.com/smithay/wayland-rs',branch='rework-317',features=["client"]}
wayland-client={git='https://github.com/smithay/wayland-rs',branch='rework-317'}
wayland-backend={git='https://github.com/smithay/wayland-rs',branch='rework-317'}
raw-window-handle='^0.3'
piet-gpu-hal={git='https://github.com/Matthias-Fauconneau/piet-gpu'}
piet-gpu={git='https://github.com/Matthias-Fauconneau/piet-gpu'}
piet-gpu-types={git='https://github.com/Matthias-Fauconneau/piet-gpu'}
piet='^0.2'

trace={git='https://github.com/Matthias-Fauconneau/trace', optional=true}
itertools={version='*', optional=true}