package={name='empty', version='0.1.0', edition='2024'}
dependencies={ui={path='../..'}}
[patch.'https://github.com/vulkano-rs/vulkano']
vulkano={path='../../../vulkano/vulkano'}
vulkano-shaders={path='../../../vulkano/vulkano-shaders'}